name: Main
on: workflow_dispatch
permissions: write-all

jobs:
  Build:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Android
            os: macos-15
            buildArgs: "android -final -ONLY_ARM64"
            cacheName: android
            artifactName: androidBuild
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
          - name: iOS
            os: macos-15
            cacheName: ios
            buildArgs: "ios -final -nosign"
            artifactName: iOSBuild
            artifactPath: "export/release/ios/build/Release-iphoneos/*.ipa"
    uses: ./.github/workflows/build.yml
    secrets:
        PSYCH_ONLINE_REPO: ${{  secrets.PSYCH_ONLINE_REPO }}
        PSYCH_ONLINE_TOKEN: ${{ secrets.PSYCH_ONLINE_TOKEN  }}
    with:
        name: ${{ matrix.name }}
        os: ${{ matrix.os }}
        cacheName: ${{ matrix.cacheName }}
        buildArgs: ${{ matrix.buildArgs }}
        artifactName: ${{ matrix.artifactName }}
        artifactPath: ${{ matrix.artifactPath }}
